name: Nightly build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  nightly-release:
    name: "Nightly release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: "marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1"  # Use commit sha to prevent supply chain attacks
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly release"
          files: |
            linux64.tar.gz
